# Generated by Django 3.2.9 on 2021-11-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211113_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='desciption',
            field=models.TextField(blank=True),
        ),
    ]
